
spring:
  redis:

    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    ssl: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:

      validation-query: select 1


blade:

  lock:
    enabled: false
    address: redis://127.0.0.1:6379

  datasource:
    dev:

      url: jdbc:mysql://localhost:3306/bladex?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: root
      password: 123456

  document:
    resources:
      - name: 授权模块
        location: /blade-auth
      - name: 工作台模块
        location: /blade-desk
      - name: 系统模块
        location: /blade-system
