#服务器端口
server:
  port: 9101

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}


audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  # 单位：毫秒
  # 单个token使用时长为1小时，token每半小时刷新一次
  expiresSecond: 3600000
  safeSecond: 1800000
